site_name: FROM FAB LABS TO FAB CITIES
site_description: Training programs & Advisory Services
site_author: Fab Lab Barcelona
site_url: https://fablabbcn.github.io/ff2fc-villas-de-cuba/
repo_name: ff2fc-villas-de-cuba
repo_url: https://github.com/fablabbcn/ff2fc-villas-de-cuba

nav:
  - Main:
      - Welcome: index.md
  - Módulo 1:
      - Introducción Fablabs: modulo_1/fablabs.md
      - Presentaciones: modulo_1/presentaciones.md
      - Visita guiada: modulo_1/ecosistemalocal.md
  - Módulo 2:
      - Introducción Fab City: modulo_2/fabcity.md
      - Presentaciones: modulo_2/presentaciones.md
      - Visita guiada: modulo_2/ateneus.md
      
theme:
  language: 'en'
  name: 'material'

  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    #- navigation.prune
    #- navigation.sections
    - navigation.tabs
    - navigation.tabs.stick
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips

  custom_dir: 'custom_theme'
  palette:
    # See assets/stylesheets/extra.css file for the color definitions
    # Palette toggle for light mode
    - scheme: mdef
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  # Logo is not yet available
  # logo: 'assets/images/logo.svg'
  # favicon: 'assets/images/favicon.ico'
  icon:
    repo: fontawesome/brands/git-alt

extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/fablabbcn'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/fablabbcn/'
    - icon: fontawesome/brands/github
      link: 'https://www.github.com/fablabbcn/'
  fullscreen_button: true

plugins:
  - macros
  - search

markdown_extensions:
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'
  - 'assets/javascripts/extra.js'
